name: PHP CI with SAST

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4' # Or whichever version you require

    - name: Install Composer dependencies
      run: composer install --no-progress --no-suggest

    - name: Run PHPStan for static analysis
      run: vendor/bin/phpstan analyze

    - name: Run PHP_CodeSniffer for code style and security analysis
      run: vendor/bin/phpcs
